# Generated by Django 5.0.3 on 2024-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibetiashop', '0003_alter_ticket_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='available_tickets',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
