# Generated by Django 5.0.3 on 2024-08-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibetiashop', '0005_produit_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_produit',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
