# Generated by Django 5.0.3 on 2024-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibetiashop', '0006_commande_code_produit_produit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom_produit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
