# Generated by Django 5.0.3 on 2024-08-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibetiashop', '0007_commande_nom_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('Contacter', 'Contacter'), ('En cours', 'En cours'), ('Livré', 'Livré')], default='Contacter', max_length=20),
        ),
    ]
